" set up Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Vundle done

syntax on
set autoindent
set backspace=indent,eol,start
set expandtab
set tabstop=4
set pastetoggle=<F3>
set cursorcolumn
set cursorline
set hlsearch
set colorcolumn=80
set number
highlight ColorColumn ctermbg = 2
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
" shortcut to switch tabs
noremap  1 1gt
noremap  2 2gt
noremap  3 3gt
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
Bundle 'craigemery/vim-autotag'
