syntax on                                                                                                                                                                     
set autoindent
set backspace=indent,eol,start
set expandtab                                                                   
set tabstop=4                                                                   
set pastetoggle=<F3>                                                            
set cursorcolumn                                                                
set cursorline                                                                  
set hlsearch                                                                    
set colorcolumn=80                                                              
set number                                                                      
highlight ColorColumn ctermbg = 2                                               
highlight ExtraWhitespace ctermbg=red guibg=red                                 
match ExtraWhitespace /\s\+$/                                                   
" shortcut to switch tabs                                                       
noremap  1 1gt                                                                  
noremap  2 2gt                                                                  
noremap  3 3gt                                                                  
nnoremap <C-h> :tabprevious<CR>                                                 
nnoremap <C-l> :tabnext<CR>
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
